-- TMF683 Party Interaction Management - Oracle DDL
-- Created for Oracle Autonomous Database 26ai with JSON native support

-- ============================================================================
-- PARTY_INTERACTION Table
-- ============================================================================
CREATE TABLE PARTY_INTERACTION (
    id                          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interaction_id              VARCHAR2(50) NOT NULL UNIQUE,
    subject                     VARCHAR2(255) NOT NULL,
    description                 CLOB,
    status                      VARCHAR2(50) NOT NULL,
    status_change_date          TIMESTAMP,
    status_change_reason        CLOB,
    channel                     VARCHAR2(50) NOT NULL,
    direction                   VARCHAR2(50) NOT NULL,
    creation_date               TIMESTAMP NOT NULL,
    initiation_date             TIMESTAMP,
    completion_date             TIMESTAMP,
    duration                    NUMBER,
    priority                    VARCHAR2(50),
    satisfaction                VARCHAR2(50),
    originating_party_id        VARCHAR2(50),
    originating_party_role      VARCHAR2(100),
    
    -- JSON native support for Oracle 26ai
    related_parties             JSON,
    related_entities            JSON,
    notes                       JSON,
    attachments                 JSON,
    characteristics             JSON,
    context_data                JSON,
    
    created_at                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by                  VARCHAR2(100),
    updated_at                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by                  VARCHAR2(100),
    
    CONSTRAINT pk_party_interaction PRIMARY KEY (id),
    CONSTRAINT uk_party_interaction_id UNIQUE (interaction_id)
);

-- Create indexes for performance
CREATE INDEX idx_pi_status ON PARTY_INTERACTION(status);
CREATE INDEX idx_pi_originating_party ON PARTY_INTERACTION(originating_party_id);
CREATE INDEX idx_pi_channel ON PARTY_INTERACTION(channel);
CREATE INDEX idx_pi_direction ON PARTY_INTERACTION(direction);
CREATE INDEX idx_pi_creation_date ON PARTY_INTERACTION(creation_date);
CREATE INDEX idx_pi_priority ON PARTY_INTERACTION(priority);

-- ============================================================================
-- PARTY_INTERACTION_SPECIFICATION Table
-- ============================================================================
CREATE TABLE PARTY_INTERACTION_SPECIFICATION (
    id                              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spec_id                         VARCHAR2(50) NOT NULL UNIQUE,
    name                            VARCHAR2(255) NOT NULL,
    description                     CLOB,
    status                          VARCHAR2(50) NOT NULL,
    status_change_date              TIMESTAMP,
    status_change_reason            CLOB,
    creation_date                   TIMESTAMP NOT NULL,
    last_update                     TIMESTAMP,
    version                         VARCHAR2(50),
    default_channel                 VARCHAR2(50),
    default_direction               VARCHAR2(50),
    default_priority                VARCHAR2(50),
    
    -- JSON native support for Oracle 26ai
    characteristics                 JSON,
    context_schema                  JSON,
    
    created_at                      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by                      VARCHAR2(100),
    updated_at                      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by                      VARCHAR2(100),
    
    CONSTRAINT pk_party_interaction_spec PRIMARY KEY (id),
    CONSTRAINT uk_party_interaction_spec_id UNIQUE (spec_id)
);

-- Create indexes for performance
CREATE INDEX idx_pis_status ON PARTY_INTERACTION_SPECIFICATION(status);
CREATE INDEX idx_pis_created_date ON PARTY_INTERACTION_SPECIFICATION(creation_date);

-- ============================================================================
-- PARTY_INTERACTION_RELATIONSHIP Table (for linking interactions)
-- ============================================================================
CREATE TABLE PARTY_INTERACTION_RELATIONSHIP (
    id                          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_interaction_id       VARCHAR2(50) NOT NULL,
    target_interaction_id       VARCHAR2(50) NOT NULL,
    relationship_type          VARCHAR2(100),
    created_at                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT pk_pi_relationship PRIMARY KEY (id),
    CONSTRAINT fk_pi_rel_source FOREIGN KEY (source_interaction_id) REFERENCES PARTY_INTERACTION(interaction_id),
    CONSTRAINT fk_pi_rel_target FOREIGN KEY (target_interaction_id) REFERENCES PARTY_INTERACTION(interaction_id)
);

CREATE INDEX idx_pi_rel_source ON PARTY_INTERACTION_RELATIONSHIP(source_interaction_id);
CREATE INDEX idx_pi_rel_target ON PARTY_INTERACTION_RELATIONSHIP(target_interaction_id);

-- ============================================================================
-- PARTY_INTERACTION_NOTE Table (for comments/notes)
-- ============================================================================
CREATE TABLE PARTY_INTERACTION_NOTE (
    id                          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interaction_id              VARCHAR2(50) NOT NULL,
    note_id                     VARCHAR2(50) NOT NULL UNIQUE,
    text                        CLOB NOT NULL,
    author                      VARCHAR2(100),
    note_date                   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_system_note              CHAR(1) DEFAULT 'N',
    
    CONSTRAINT pk_pi_note PRIMARY KEY (id),
    CONSTRAINT fk_pi_note_interaction FOREIGN KEY (interaction_id) REFERENCES PARTY_INTERACTION(interaction_id)
);

CREATE INDEX idx_pi_note_interaction ON PARTY_INTERACTION_NOTE(interaction_id);
CREATE INDEX idx_pi_note_date ON PARTY_INTERACTION_NOTE(note_date);

-- ============================================================================
-- PARTY_INTERACTION_STATUS_HISTORY Table (for audit trail)
-- ============================================================================
CREATE TABLE PARTY_INTERACTION_STATUS_HISTORY (
    id                          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interaction_id              VARCHAR2(50) NOT NULL,
    old_status                  VARCHAR2(50),
    new_status                  VARCHAR2(50) NOT NULL,
    change_reason               VARCHAR2(500),
    changed_by                  VARCHAR2(100),
    changed_at                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT pk_pi_status_history PRIMARY KEY (id),
    CONSTRAINT fk_pi_status_history_interaction FOREIGN KEY (interaction_id) REFERENCES PARTY_INTERACTION(interaction_id)
);

CREATE INDEX idx_pi_status_hist_interaction ON PARTY_INTERACTION_STATUS_HISTORY(interaction_id);
CREATE INDEX idx_pi_status_hist_date ON PARTY_INTERACTION_STATUS_HISTORY(changed_at);

-- ============================================================================
-- Triggers for automatic timestamp updates
-- ============================================================================
CREATE OR REPLACE TRIGGER trg_party_interaction_update
BEFORE UPDATE ON PARTY_INTERACTION
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_party_interaction_spec_update
BEFORE UPDATE ON PARTY_INTERACTION_SPECIFICATION
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ============================================================================
-- Views for common queries
-- ============================================================================

-- View for active interactions
CREATE OR REPLACE VIEW v_active_party_interactions AS
SELECT 
    interaction_id,
    subject,
    description,
    status,
    channel,
    direction,
    priority,
    originating_party_id,
    creation_date,
    created_by
FROM PARTY_INTERACTION
WHERE status IN ('initiated', 'active')
ORDER BY creation_date DESC;

-- View for completed interactions
CREATE OR REPLACE VIEW v_completed_party_interactions AS
SELECT 
    interaction_id,
    subject,
    channel,
    direction,
    priority,
    satisfaction,
    originating_party_id,
    creation_date,
    completion_date,
    TRUNC((completion_date - creation_date) * 86400) AS duration_seconds
FROM PARTY_INTERACTION
WHERE status = 'completed'
ORDER BY completion_date DESC;

-- View for interaction statistics
CREATE OR REPLACE VIEW v_party_interaction_statistics AS
SELECT 
    status,
    channel,
    COUNT(*) as interaction_count,
    AVG(TRUNC(SYSDATE) - TRUNC(creation_date)) as avg_age_days
FROM PARTY_INTERACTION
GROUP BY status, channel;

-- ============================================================================
-- Comments for documentation
-- ============================================================================
COMMENT ON TABLE PARTY_INTERACTION IS 'TMF683 Party Interaction Management - Main interaction table with JSON native support';
COMMENT ON TABLE PARTY_INTERACTION_SPECIFICATION IS 'TMF683 Party Interaction Specification - Templates for interaction creation';
COMMENT ON COLUMN PARTY_INTERACTION.related_parties IS 'JSON array of related parties';
COMMENT ON COLUMN PARTY_INTERACTION.related_entities IS 'JSON array of related entities (tickets, orders, etc.)';
COMMENT ON COLUMN PARTY_INTERACTION.notes IS 'JSON array of notes/comments';
COMMENT ON COLUMN PARTY_INTERACTION.attachments IS 'JSON array of file attachments';
COMMENT ON COLUMN PARTY_INTERACTION.characteristics IS 'JSON array of custom characteristics';
COMMENT ON COLUMN PARTY_INTERACTION.context_data IS 'JSON object for custom/extensible data';

COMMIT;
